name: fritter
description: An open-source Twitter client

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 3.0.0-beta3+20220904

environment:
  sdk: ">=2.17.0 <3.0.0"

dependency_overrides:
  auto_direction:
    git:
      url: https://github.com/AhmedAlYousif/auto_direction.git
      ref: 41e091d1bcef2f710e10ca88e72d05ea182135d7
  catcher:
    git:
      url: https://github.com/ThexXTURBOXx/catcher.git
      ref: 5c1df82b56339fe534058594f8f72c327c9cab85
  flutter_iconpicker:
    git:
      url: https://github.com/Ahmadre/FlutterIconPicker.git
      ref: bae6bb92d815efac1a1fded14b0d6573bdcdcaa1
  multi_select_flutter:
    git:
      url: https://github.com/kabagouda/multi_select_flutter.git
      ref: abda500eae263fcd6b26d09f3c68d5fb9591df85
  pref:
    git:
      url: https://github.com/jonjomckay/flutter_pref.git
      ref: 04ffdce
      path: pref

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.3

  async_button_builder: ^2.3.0+1
  auto_direction: ^0.0.6
  catcher: ^0.6.9
  chewie: ^1.3.4
  dart_twitter_api: ^0.5.6+1
  device_info_plus: ^4.1.2
  device_preview: ^1.1.0
  dio: ^4.0.6
  dotted_border: ^2.0.0+2
  extended_image: ^6.2.1
  faker: ^2.0.0
  ffcache: ^1.1.0
  flex_color_scheme: ^5.0.1
  flutter_cache: ^0.1.0
  file_picker: ^5.0.1
  flutter_colorpicker: ^1.0.3
  flutter_file_dialog: ^2.3.0
  flutter_iconpicker: ^3.1.4+1
  flutter_local_notifications: ^10.0.0-dev.20
  flutter_localized_locales: ^2.0.3
  flutter_triple: ^1.2.7+2
  flutter_windowmanager: ^0.2.0
  html_unescape: ^2.0.0
  http: ^0.13.4
  infinite_scroll_pagination: ^3.2.0
  intl: ^0.17.0
  logging: ^1.0.2
  measure_size: ^3.0.1
  multi_select_flutter: ^4.1.2
  package_info: ^2.0.2
  path: ^1.8.1
  path_provider: ^2.0.11
  permission_handler: ^8.2.5
  pref: ^2.6.0
  quiver: ^3.1.0
  scroll_bottom_navigation_bar: ^4.0.0
  scroll_to_index: ^3.0.1
  sentry_flutter: ^6.6.1
  share: ^2.0.4
  simple_icons: ^7.1.0
  sqflite: ^2.0.2+1
  sqflite_common: ^2.2.1+1
  sqflite_migration_plan: ^1.0.0
  timeago: ^3.2.2
  uni_links2: ^0.6.0+2
  url_launcher: ^6.1.4
  uuid: ^3.0.6
  video_player: ^2.4.5
  visibility_detector: ^0.3.3
  wakelock: ^0.6.2

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.9.3
  flutter_lints:
  flutter_oss_licenses: ^2.0.1
  intl_utils: ^2.6.1
  sqflite_common_ffi: ^2.1.1+1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icon.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  generate: true

flutter_intl:
  enabled: true
  class_name: L10n
