name: fritter
description: An open-source Twitter client

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 3.0.0-beta9+300001014

environment:
  sdk: ">=2.18.0 <3.0.0"

dependency_overrides:
  intl: any
  auto_direction:
    git:
      url: https://github.com/AhmedAlYousif/auto_direction.git
      ref: 41e091d1bcef2f710e10ca88e72d05ea182135d7
  # Required until device_info_plus updates, as it transitively depends on an old version
  file: ^6.1.4
  # TODO: Remove once https://github.com/Ahmadre/FlutterIconPicker/pull/54 is merged


dependencies:
  flutter:
    sdk: flutter

  package_info_plus: ^3.1.1
  async_button_builder: ^2.3.0+1
  auto_direction: ^0.0.6
  chewie: ^1.3.6
  dart_twitter_api: ^0.5.7+1
  device_info_plus: ^8.2.0
  device_preview: ^1.1.0
  dotted_border: ^2.0.0+3
  extended_image: ^8.0.2
  extended_nested_scroll_view: ^6.1.1
  faker: ^2.1.0
  ffcache: ^1.1.0
  flex_color_scheme: ^6.1.1
  flutter_cache: ^0.1.0
  file_picker: ^5.2.3
  flutter_colorpicker: ^1.0.3
  flutter_file_dialog: ^2.3.2
  flutter_iconpicker: ^3.2.4
  flutter_local_notifications: ^12.0.4
  flutter_localized_locales: ^2.0.3
  flutter_triple: ^1.2.7+4
  flutter_windowmanager: ^0.2.0
  html_unescape: ^2.0.0
  http: ^0.13.5
  infinite_scroll_pagination: ^3.2.0
  intl: ^0.17.0
  logging: ^1.1.0
  measure_size: ^4.0.0
  multi_select_flutter: ^4.1.3
  package_info: ^2.0.2
  path: ^1.8.2
  path_provider: ^2.0.11
  permission_handler: ^10.2.0
  pref: ^2.7.0
  provider: ^6.0.4
  quiver: ^3.1.0
  scroll_bottom_navigation_bar: ^4.0.0
  scroll_to_index: ^3.0.1
  sentry_flutter: ^7.4.2
  share: ^2.0.4
  share_plus: ^6.2.0
  simple_icons: ^7.10.0
  sqflite: ^2.2.2
  sqflite_common: ^2.4.0+2
  sqflite_migration_plan: ^1.0.0
  timeago: ^3.3.0
  uni_links2: ^0.6.0+2
  url_launcher: ^6.1.7
  uuid: ^3.0.7
  video_player: ^2.4.9
  visibility_detector: ^0.4.0
  wakelock: ^0.6.2

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.11.0
  flutter_lints:
  flutter_oss_licenses: ^2.0.1
  intl_utils: ^2.8.1
  sqflite_common_ffi: ^2.2.0+1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icon.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  generate: true

flutter_intl:
  enabled: true
  class_name: L10n
